"https://{default}/":
    type: upstream
    upstream: "frontapp:http"
    cache:
        # Cache is managed by Fastly
        enabled: false

"https://serviceapi.{default}/":
    type: upstream
    upstream: "serviceapi:http"
    cache:
        # Cache is managed by Fastly
        enabled: false
